### ISSUE TITLE
Actually publish version 2.0.3 to npm

### ISSUE THREAD

**Issue by lumaxis** [moxystudio/node-fetch-coverage#34]
@satazor It seems like `2.0.3` was merged, added to the Changelog, and published as a release on GitHub but never actually published to npm: https://www.npmjs.com/package/fetch-coverage

Would be great if you could do that 🙇🏼‍♂️

**Comment by acostalima** [comment]
@lumaxis sorry for the long delay 🙏 
It's published now!

**Comment by lumaxis** [comment]
No worries, better late than never! 😄 Thanks 🥳
