### ISSUE TITLE
Returns null where it should return .99

### ISSUE THREAD

**Issue by dsifford** [moxystudio/node-fetch-coverage#5]
Hi,

I opened an issue about this in the npms main repo, but I have tracked it down to being an issue between this module as well as `node-detect-repo-test-files` (I'll be opening an issue there as well).

I've pulled both repos and tried locally and I can consistently reproduce the failure.

The repo in question is here: https://github.com/aliemteam/wp-graphql

Happy to help if needed. I'd like to be scored fairly.

**Comment by satazor** [comment]
Your module is using codecov which we do support. Need to investigate.

**Comment by dsifford** [comment]
@satazor Looks like codecov isn't listed here: https://github.com/IndigoUnited/node-fetch-coverage/blob/master/index.js#L59

Could that be the issue?

**Comment by satazor** [comment]
Aha it seems so, we totally forgot to add codecov there.
